/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  sdai
 * Created: Nov 29, 2016
 */
CREATE TABLE User(Id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, Username VARCHAR(50) NOT NULL, Credential BINARY(8192));
CREATE TABLE User_Associate(UserId BIGINT UNSIGNED NOT NULL, Name VARCHAR(50) NOT NULL, CONSTRAINT USER_ASSOCIATES_MAPPING FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE);
CREATE TABLE User_Message(Id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, UserId BIGINT UNSIGNED NOT NULL, Type Int NOT NULL, Source VARCHAR(50), Target VARCHAR(50), Data CLOB(52428800), Attr BLOB(51200), MessageTime TIMESTAMP NOT NULL, CONSTRAINT USER_MESSAGE_MAPPING FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE);
CREATE TABLE User_Message_Attr(PayloadId BIGINT UNSIGNED NOT NULL, Key VARCHAR(50) NOT NULL, Value CLOB(10240), CONSTRAINT USER_MESSAGE_ATTR_MAPPING FOREIGN KEY (PayloadId) REFERENCES User_Message(Id) ON DELETE CASCADE);